import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import AppBar from '@/components/Lottery/AppBar';
import Wagmi from './wagmi';

const inter = Inter({
  subsets: ['latin'],
  weight: ['300', '400', '500', '700', '800'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className='dark backdrop-blur-sm'>
      <body
        className={`dark:bg-gray-900 dark:text-gray-100 ${inter.className}`}
      >
        <AppBar />
        {children}
      </body>
    </html>
  );
}
